### ISSUE TITLE
Change these badges to labels

### ISSUE THREAD

**Issue by icyflame** [icyflame/erp-rails#61]
https://github.com/icyflame/erp-rails/blob/master/app/views/viewall/students.html.erb#L67

@aniarya82 

Here, there is an unnecessary anchor element, that points nowhere. Instead use labels, as they are better looking.

http://getbootstrap.com/components/#labels

**Comment by aniarya82** [comment]
As you said the UI of labels is screwed up thats why the display get
screwed when i use labels

On Sun, Jun 14, 2015 at 9:26 AM, Siddharth Kannan <notifications@github.com>
wrote:

>
> https://github.com/icyflame/erp-rails/blob/master/app/views/viewall/students.html.erb#L67
>
> @aniarya82 <https://github.com/aniarya82>
>
> Here, there is an unnecessary anchor element, that points nowhere. Instead
> use labels, as they are better looking.
>
> http://getbootstrap.com/components/#labels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icyflame/erp-rails/issues/61>.
>



-- 

*Regards,*

*Hiten Chowdhary*

*Undergraduate Student*

*Department of Mathematics*

*IIT Kharagpur*

*Ph: +919800111032*

**Comment by icyflame** [comment]
@aniarya82 

Sorry, what I meant was the the UI of badges is screwed up for our use.

Checkout the bootstrap page. I have implemented those exact labels on another website, and they look good. Just avoid using the `info` and the `default` color, as it is not good.

The other colors are good, and the text is clearly visible.

![image](https://cloud.githubusercontent.com/assets/3668034/8147055/a29499e4-1279-11e5-90af-4dc19df1aeef.png)

**Comment by aniarya82** [comment]
are dada, i m telling na bekar ho jayega

**Comment by icyflame** [comment]
See, the badges need to have an anchor element, and that's useless, as it points no where. So, we should shift to labels, they look better.

**Comment by aniarya82** [comment]
see for urself, matlab i m saying that it gets bad but you won't believe man :/
![screen shot 2015-06-14 at 9 52 19 am](https://cloud.githubusercontent.com/assets/7463217/8147075/2e7eb9ac-127b-11e5-988a-66f7dcc52dc2.png)

**Comment by aniarya82** [comment]
And this will happen when labels are added
![screen shot 2015-06-14 at 9 54 38 am](https://cloud.githubusercontent.com/assets/7463217/8147083/6e3aea7a-127b-11e5-81c7-54c7e8aeb349.png)

**Comment by aniarya82** [comment]
now if you like this shitty ui then no problem

**Comment by icyflame** [comment]
@aniarya82 
Why are the numbers getting the black circle around them? If they are a part of the span that the label has, then that shouldn't happen. They should render in the font of `Positive` with white color.

**Comment by aniarya82** [comment]
here black removed
![screen shot 2015-06-14 at 9 57 45 am](https://cloud.githubusercontent.com/assets/7463217/8147089/d65f16f8-127b-11e5-9b3e-1c83ee4e44fa.png)

**Comment by icyflame** [comment]
@aniarya82 
Add spacing between two labels, using `padding-left` and `padding-right`. Then, the UI should look much better.

**Comment by icyflame** [comment]
@aniarya82 
Make the same changes in #60 and push these changes to a new PR.
